name: freerasp_example
description: Demonstrates how to use the freerasp plugin.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  freerasp:
    # When depending on this package from a real application you should use:
    #   freerasp: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  google_fonts: ^6.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true