name: freerasp
description: Flutter library for improving app security and threat monitoring on Android and iOS mobile devices. Learn more about provided features on the freeRASP's homepage first.
version: 6.8.0
homepage: https://www.talsec.app/freerasp-in-app-protection-security-talsec
repository: https://github.com/talsec/Free-RASP-Flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - app-shielding
  - rasp
  - reverse-engineering
  - application-security
  - freerasp

dependencies:
  convert: ^3.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.11
  json_annotation: ^4.0.1
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mocktail: ^1.0.4
  pigeon: ^22.4.0
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aheaditec.freerasp
        pluginClass: FreeraspPlugin
      ios:
        pluginClass: FreeraspPlugin
