name: freerasp
description: Flutter library for improving app security and threat monitoring on Android and iOS mobile devices. Learn more about provided features on the freeRASP's homepage first.
version: 3.0.2
homepage: https://www.talsec.app/freerasp-in-app-protection-security-talsec
repository: https://github.com/talsec/Free-RASP-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  convert: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  extra_pedantic: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aheaditec.freerasp
        pluginClass: FreeraspPlugin
      ios:
        pluginClass: FreeraspPlugin